//
//  SignInAttemptSecondFactor.swift
//  Clerk
//
//  Created by Mike Pitre on 1/21/25.
//

import Foundation

extension SignIn {
  
  /// A parameter object for attempting the second factor verification process.
  public struct AttemptSecondFactorParams: Encodable {
    /// The strategy used for second factor verification.
    public let strategy: String
    
    /// The verification code sent to the user or generated by the authenticator app.
    public let code: String
  }
  
  /// A strategy for attempting the second factor verification process.
  public enum AttemptSecondFactorStrategy: Sendable {
    /// User will receive a one-time authentication code via SMS. The code should be provided as part of the verification process.
    case phoneCode(code: String)
    
    /// User must provide a 6-digit TOTP code generated by their authenticator app.
    case totp(code: String)
    
    /// User can provide a backup code for verification.
    case backupCode(code: String)
    
    /// Converts the strategy to parameters for the second factor verification process.
    ///
    /// - Returns: An `AttemptSecondFactorParams` object containing the strategy and the verification code.
    var params: AttemptSecondFactorParams {
      switch self {
      case .phoneCode(let code):
        return .init(strategy: "phone_code", code: code)
      case .totp(let code):
        return .init(strategy: "totp", code: code)
      case .backupCode(let code):
        return .init(strategy: "backup_code", code: code)
      }
    }
  }
}
