# SwiftLint Configuration for Clerk iOS SDK

# Disabled rules that conflict with SwiftFormat or project preferences
disabled_rules:
  - trailing_whitespace  # SwiftFormat handles this
  - line_length  # SwiftFormat handles this (maxwidth 1000)
  - indentation_width  # SwiftFormat handles this (indent 2)
  - trailing_comma  # Allow trailing commas (SwiftFormat adds them)
  - todo  # Allow TODO comments
  - nesting  # Allow nested types
  - opening_brace  # Allow wrapped opening braces (on new line)

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_first_last
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Paths to ignore
excluded:
  - Examples
  - .build
  - DerivedData
  - build
  - Tests

# Reporter type
reporter: "xcode"
