//
//  SignInFactorTwoTotpCodeView.swift
//
//
//  Created by Mike Pitre on 1/9/24.
//

#if os(iOS)

import SwiftUI

struct SignInFactorTwoTotpCodeView: View {
    var clerk = Clerk.shared
    @Environment(ClerkUIState.self) private var clerkUIState
    @Environment(AuthView.Config.self) private var config
    @State private var errorWrapper: ErrorWrapper?
    
    let factor: SignInFactor
    
    private var signIn: SignIn? {
        clerk.client?.signIn
    }
    
    var body: some View {
        @Bindable var config = config
        
        ScrollView {
            VStack(spacing: .zero) {
                OrgLogoView()
                    .frame(width: 32, height: 32)
                    .padding(.bottom, 24)
                
                VerificationCodeView(
                    code: $config.signInFactorTwoTOTPCode,
                    title: "Two-step verification",
                    subtitle: "To continue, please enter the verification code generated by your authenticator app"
                )
                .onCodeEntry {
                    await attempt()
                }
                .onContinueAction {
                    //
                }
                .onUseAlernateMethod {
                    clerkUIState.presentedAuthStep = .signInFactorTwoUseAnotherMethod(
                        currentFactor: factor
                    )
                }
            }
            .padding(.horizontal)
            .padding(.vertical, 32)
            .clerkErrorPresenting($errorWrapper)
        }
    }
    
    private func attempt() async {
        do {
            try await signIn?.attemptSecondFactor(
                for: .totp(code: config.signInFactorTwoTOTPCode)
            )
            clerkUIState.setAuthStepToCurrentSignInStatus()
        } catch {
            errorWrapper = ErrorWrapper(error: error)
            config.signInFactorTwoTOTPCode = ""
            dump(error)
        }
    }
}

#Preview {
    SignInFactorTwoTotpCodeView(factor: .mock)
}

#endif
