//
//  SignInFactorTwoTotpCodeView.swift
//
//
//  Created by Mike Pitre on 1/9/24.
//

#if os(iOS)

import SwiftUI

struct SignInFactorTwoTotpCodeView: View {
    @ObservedObject private var clerk = Clerk.shared
    @EnvironmentObject private var clerkUIState: ClerkUIState
    @EnvironmentObject private var config: AuthView.Config
    @State private var errorWrapper: ErrorWrapper?
    
    let signIn: SignIn
    
    var body: some View {
        ScrollView {
            VStack(spacing: .zero) {
                OrgLogoView()
                    .frame(width: 32, height: 32)
                    .padding(.bottom, 24)
                
                VerificationCodeView(
                    code: $config.signInFactorTwoTOTPCode,
                    title: "Two-step verification",
                    subtitle: "To continue, please enter the verification code generated by your authenticator app"
                )
                .onCodeEntry {
                    await attempt()
                }
                .onContinueAction {
                    //
                }
                .onUseAlernateMethod {
                    clerkUIState.presentedAuthStep = .signInFactorTwoUseAnotherMethod(
                        signIn: signIn,
                        currentFactor: signIn.secondFactor(for: .totp)
                    )
                }
            }
            .padding(.horizontal)
            .padding(.vertical, 32)
            .clerkErrorPresenting($errorWrapper)
        }
    }
    
    private func attempt() async {
        do {
            let attemptedSignIn = try await signIn.attemptSecondFactor(
                for: .totp(code: config.signInFactorTwoTOTPCode)
            )
            clerkUIState.setAuthStepToCurrentStatus(for: attemptedSignIn)
        } catch {
            errorWrapper = ErrorWrapper(error: error)
            config.signInFactorTwoTOTPCode = ""
            dump(error)
        }
    }
}

#Preview {
    SignInFactorTwoTotpCodeView(signIn: .mock)
}

#endif
