import ClerkSnapshots
import Foundation

public typealias BillingMoneyAmount = ClerkSnapshots.BillingMoneyAmount
public typealias BillingPerUnitTotalTier = ClerkSnapshots.BillingPerUnitTotalTier
public typealias BillingPerUnitTotal = ClerkSnapshots.BillingPerUnitTotal
