// Generated by @clerk/mobile-runtime pack. Do not edit.
import Foundation
public enum BundledCore {
  public static let sha256 = "6cd315d54c73b4b62780c95092aa024cbf4fa1f836d99512915f20fc77112168"
  public static let coreRevision = "494f27590336e85d7e915b61dbfa8349edbd1b45"
}
