// Generated by @clerk/mobile-runtime pack. Do not edit.
import Foundation
public enum BundledCore {
  public static let sha256 = "3c4ea6180da6abd15f6112ce669a8f51a4f48fb389acc2f45331e411323a7bf4"
  public static let coreRevision = "acfc5359dab0eca6a46ceed3282f2057bc0321f2"
}
