// Generated by @clerk/mobile-runtime pack. Do not edit.
import Foundation
public enum BundledCore {
  public static let sha256 = "fad4b7276096eec0700db8e46f9b814ed1fd927f6c0929a82a01e722e8616294"
  public static let coreRevision = "d33cc3d0b20a0492b5865cdedba6bf7d58b98362"
}
