name: Checks

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    name: Shared checks
    permissions:
      actions: read
      contents: read
      statuses: write
    uses: ./.github/workflows/shared-checks.yml
    secrets: inherit
