name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: true  # Fail fast on the first failure in the matrix
      matrix:
        swift-version: [5.10, 6.0]  # Adjusted to Swift versions 5.10 and 6.0
        platform: [iOS, macCatalyst, macOS, tvOS, visionOS, watchOS]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Swift
      uses: actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}

    - name: Install dependencies
      run: swift package resolve

    - name: Build for ${{ matrix.platform }} with Swift ${{ matrix.swift-version }}
      run: |
        if [[ "${{ matrix.platform }}" == "iOS" ]]; then
          swift build -x ios
        elif [[ "${{ matrix.platform }}" == "macCatalyst" ]]; then
          swift build -x macCatalyst
        elif [[ "${{ matrix.platform }}" == "macOS" ]]; then
          swift build -x macos
        elif [[ "${{ matrix.platform }}" == "tvOS" ]]; then
          swift build -x tvOS
        elif [[ "${{ matrix.platform }}" == "visionOS" ]]; then
          swift build -x visionOS
        elif [[ "${{ matrix.platform }}" == "watchOS" ]]; then
          swift build -x watchOS
        fi

    - name: Run tests
      run: swift test
