name: SwiftLint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict --config .swiftlint.yml


