name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.spi.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macOS-14
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 15"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=visionOS Simulator,name=Apple Vision Pro"
          - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
          - "platform=macOS,variant=Mac Catalyst"

    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme ClerkSDK -destination "${{ matrix.destination }}" test | xcbeautify
