# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["15.0"]
        include:
          - xcode: "15.0.0"
            macos: macOS-13
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v1
      - name: Build
        run: swift build
      - name: Run Tests
        run: swift test

#jobs:
#  build:
#
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: swift-actions/setup-swift@v1
#      - name: Build
#        run: swift build
#      - name: Run tests
#        run: swift test
